version: '2.3'

services:

  detectron-api:
    image: detectron-api
    container_name: detectron-api
    working_dir: /detectron-api
    build:
      context: ../
      dockerfile: docker/Dockerfile
    ports:
      - 5000:5000
    volumes:
      - ../:/detectron-api
    runtime: nvidia
    restart: always
    command: python3 app.py